author = "Yoshiharu Yamashita"
baseurl = "https://gc-manual.netlify.com/"
canonifyurls = false
copyright = "&copy; 2016. All rights reserved."
paginate = 10
title = "Blackburn Theme Demo"
[indexes]
product = "make"
tag = "tags"
topic = "topics"
[languages.en]
languageCode = "en-us"
languageName = "USD"
title = "USD"
weight = 1
[languages.fr]
languageCode = "fr"
languageName = "GBP"
title = "GBP"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4
[params]
brand = "Blackburn"
dateformat = "2006-01-02T00:00:00+00:00"
disqus = "Your Disqus shortname"
googleanalytics = "Your Google Analytics tracking ID"
highlightjs = "androidstudio"
subtitle = "A Hugo Theme"
[social]
facebook = "*"
github = "yoshiharuyamashita"
instagram = "*"
linkedin = "*"
stackoverflow = "*"
twitter = "*"
[taxonomy]
product = "make"
