---
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  manuals:
    default_front_matter_template: 1984-bmw-3-series-e30-318i-5913cf1d-646b-42c8-a918-fd42a9729482
version: 0.25.1
