---
hide_body: false
fields:
- name: car_ID
  label: Car id
  type: text
  hidden: false
  default: ''
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: download_ID
  label: Download id
  type: text
  hidden: false
  default: ''
- name: website
  label: Website
  type: text
  hidden: false
  default: ''
- name: make
  label: Make
  type: tag_list
  hidden: false
  default: ''
- name: serie
  label: Serie
  type: text
  hidden: false
  default: ''
- name: sub_serie
  label: Sub serie
  type: text
  hidden: false
  default: ''
- name: platform
  label: Platform
  type: text
  hidden: false
  default: ''
- name: engine
  label: Engine
  type: text
  hidden: false
  default: ''
- name: year
  label: Year
  type: text
  hidden: false
  default: ''
- name: body_type
  label: Body type
  type: text
  hidden: false
  default: ''
- name: fuel_type
  label: Fuel type
  type: text
  hidden: false
  default: ''
- name: engine_long
  label: Engine long
  type: text
  hidden: false
  default: ''
- name: cylinders
  label: Cylinders
  type: text
  hidden: false
  default: ''
- name: displacement
  label: Displacement
  type: text
  hidden: false
  default: ''
- name: power_kw
  label: Power kw
  type: text
  hidden: false
  default: ''
- name: horse_power
  label: Horse power
  type: text
  hidden: false
  default: ''
- name: torque_Nm
  label: Torque nm
  type: text
  hidden: false
  default: ''
- name: manual_covers
  label: Manual covers
  type: text
  hidden: false
  default: ''
- name: table_of_content
  label: Table of content
  type: textarea
  hidden: false
  default: ''
- name: currency
  label: Currency
  type: text
  hidden: false
  default: ''
- name: price
  label: Price
  type: text
  hidden: false
  default: ''
- name: sendowl
  label: Sendowl
  type: textarea
  hidden: false
  default: ''
- name: productpage_image
  label: Productpage image
  type: text
  hidden: false
  default: ''
- name: catpage_image
  label: Catpage image
  type: text
  hidden: false
  default: ''
- name: manual_type
  label: Manual type
  type: text
  hidden: false
  default: ''
- name: manual_pages
  label: Manual pages
  type: text
  hidden: false
  default: ''
- name: manual_size
  label: Manual size
  type: text
  hidden: false
  default: ''
- name: manual_file_type
  label: Manual file type
  type: text
  hidden: false
  default: ''
- name: language
  label: Language
  type: text
  hidden: false
  default: ''
- name: preview_01
  label: Preview 01
  type: text
  hidden: false
  default: ''
- name: preview_02
  label: Preview 02
  type: text
  hidden: false
  default: ''
- name: preview_03
  label: Preview 03
  type: text
  hidden: false
  default: ''
- name: preview_04
  label: Preview 04
  type: text
  hidden: false
  default: ''
- name: car_image_01
  label: Car image 01
  type: text
  hidden: false
  default: ''
- name: car_image_02
  label: Car image 02
  type: text
  hidden: false
  default: ''
- name: car_image_03
  label: Car image 03
  type: text
  hidden: false
  default: ''
- name: car_image_04
  label: Car image 04
  type: text
  hidden: false
  default: ''
- name: car_image_05
  label: Car image 05
  type: text
  hidden: false
  default: ''
- name: related_products_01
  label: Related products 01
  type: text
  hidden: false
  default: ''
- name: related_products_02
  label: Related products 02
  type: text
  hidden: false
  default: ''
- name: related_products_03
  label: Related products 03
  type: text
  hidden: false
  default: ''
- name: related_products_04
  label: Related products 04
  type: text
  hidden: false
  default: ''
- name: product_groups_01
  label: Product groups 01
  type: text
  hidden: false
  default: ''
- name: product_groups_02
  label: Product groups 02
  type: text
  hidden: false
  default: ''
- name: product_groups_03
  label: Product groups 03
  type: text
  hidden: false
  default: ''
- name: product_groups_04
  label: Product groups 04
  type: text
  hidden: false
  default: ''
- name: product_groups_05
  label: Product groups 05
  type: text
  hidden: false
  default: ''
- name: product_groups_06
  label: Product groups 06
  type: text
  hidden: false
  default: ''
- name: part_gr_advantages
  label: Part gr advantages
  type: text
  hidden: false
  default: ''
- name: part_gr_add_to_cart
  label: Part gr add to cart
  type: text
  hidden: false
  default: ''
- name: part_gr_downloads
  label: Part gr downloads
  type: text
  hidden: false
  default: ''
- name: id
  label: Id
  type: text
  hidden: false
  default: ''
- name: type
  label: Type
  type: text
  hidden: false
  default: ''
- type: text
  label: Make2
  name: make_2
